version: "3.9"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.6
    container_name: tp1_heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config_heimdall:/config
  swag:
    container_name: tp1_swag
    image: lscr.io/linuxserver/swag:2.6.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=tpco.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DNSPLUGIN=duckdns
      - DUCKDNSTOKEN=89f727a1-e2a8-43a2-b804-20b82d48071e
    depends_on:
      - heimdall
    volumes:
      - ./config_swag:/config
    ports:
      - "80:80"
      - "443:443"
  tldraw:
    build: tldraw
  #   ports:
  #    - 5173:5173