version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOSTS=mariadb,mysql
  phppgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: colin@ynov.com
      PGADMIN_DEFAULT_PASSWORD: root
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.6
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config_heimdall:/config
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config_nextcloud:/config
      - ./data_nextcloud:/data
    restart: unless-stopped
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - './openldap_data:/bitnami/openldap'
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:2.6.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=tpco.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DNSPLUGIN=duckdns
      - DUCKDNSTOKEN=89f727a1-e2a8-43a2-b804-20b82d48071e
    depends_on:
      - heimdall
      - phpmyadmin
      - phppgadmin
      - nextcloud
    volumes:
      - ./config_swag:/config
    ports:
      - "80:80"
      - "443:443"
  tldraw:
    build: tldraw
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    tty: true
    stdin_open: true
    domainname: "example.org"
    hostname: "ldap-server"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
  plik:
    image: rootgg/plik:latest
    container_name: plik
    restart: "unless-stopped"